name: 'Install Node.js and dependencies'

description: 'Set up Node and dependencies'
runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18.17.0
    - name: Install pnpm
      shell: bash
      run: npm install -g pnpm
    - name: Install dependencies
      shell: bash
      run: pnpm install