name: Frontend Actions
on:
  push:
    paths:
      - 'apps/web/**'
jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Node and dependencies
        uses: ./.github/actions/install
      - name: Run lint
        run: pnpm dlx nx lint web